Fixes #33 - better method compilation error handling
We now use the Pharo smalltalk editor's notification for method compile errors which actually inserts itself in the text without obscuring other text. 
See JadeiteTextDocument>>reportCompileError: & JadeiteMorphicCodeAdapter>>buildWidget
https://github.com/GemTalk/JadeiteForPharo/issues/33

After abort, updateProjects so we make sure to get rid of removed packages. 
Clean up filter & method list clearing code. When the class changes, then do the clear and remove that code from the package & project selection dependencies. 
Removed a few references to the ported class ListModel
Discovered a missing period in an initialization method

Ported a few browser tests into the pharo client tests